### ISSUE TITLE
Empty file causes server exception

### ISSUE THREAD

**Issue by carlwilson** [veraPDF/veraPDF-rest#15]
- client should detect no file selected
- server should catch empty file

**Comment by carlwilson** [comment]
Server exception:

    java.io.IOException: Error: End-of-File, expected line
        at org.apache.pdfbox.pdfparser.BaseParser.readLine(BaseParser.java:1161)
        at org.apache.pdfbox.pdfparser.COSParser.parseHeader(COSParser.java:1984)
        at org.apache.pdfbox.pdfparser.COSParser.parsePDFHeader(COSParser.java:1961)
        at org.apache.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:264)
        at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1064)
        at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:938)
        at org.verapdf.model.ModelParser.createModelWithFlavour(ModelParser.java:38)
        at org.verapdf.rest.resources.ValidateResource.validate(ValidateResource.java:43)

**Comment by carlwilson** [comment]
Moved client detection to #19
