### ISSUE TITLE
java.lang.IllegalStateException: You need to provide an instance of SwaggerBundleConfiguration

### ISSUE THREAD

**Issue by alexis-via** [veraPDF/veraPDF-rest#56]
Following the merge of the PR https://github.com/veraPDF/veraPDF-rest/pull/53
when I try to start veraPDF-rest, I get a Java backtrace:

```
% java -jar target/verapdf-rest-0.1.0-SNAPSHOT.jar server
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.fasterxml.jackson.module.afterburner.util.MyClassLoader (file:/home/alexis/new_boite/dev/veraPDF-rest/target/verapdf-rest-0.1.0-SNAPSHOT.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.module.afterburner.util.MyClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO  [2021-03-29 08:48:39,565] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2021-03-29 08:48:39,568] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2021-03-29 08:48:39,568] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: css for path /css/*
INFO  [2021-03-29 08:48:39,585] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: js for path /js/*
INFO  [2021-03-29 08:48:39,585] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: img for path /img/*
java.lang.IllegalStateException: You need to provide an instance of SwaggerBundleConfiguration
at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:59)
at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:46)
at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
at io.dropwizard.cli.Cli.run(Cli.java:78)
at io.dropwizard.Application.run(Application.java:93)
at org.verapdf.rest.app.VeraPdfRestApplication.main(VeraPdfRestApplication.java:45)
zsh: exit 1     java -jar target/verapdf-rest-0.1.0-SNAPSHOT.jar server
```

I'm on Ubuntu 20.04 LTS with openJDK 11 (same error with openJDK 14). I'm not the only one to have this problem, cf the comments in the PR.

The workaround is to checkout the code before the merge of the PR:
```
git checkout 7f1970f81d3d55e1804dafbc60596d3f2c5cfb38
mvn clean package
```
Then veraPDF-rest starts without problem.

**Comment by bdoubrov** [comment]
Swagger is supported in the latest version. See README
